### ISSUE TITLE
Error running STIR demo.ipynb

### ISSUE THREAD

**Issue by hrashidykanan** [olivierverdier/odlpet#1]
Dear Olivier,

Hope you are doing well.

I installed the newest version of STIR (Version 6), ODL and ODLpet packages on our server. I can import all the mentioned packages, however, when I try to run the "STIR demo.ipynb" code from the examples you provided, I get the following error running "proj = c.get_projector()" (cell 5):

ValueError: No default scanner of name Userdefined

Could you please help me in this regard?

Thank you very much.

**Comment by olivierverdier** [comment]
Thank you for reporting this. I don't have access to a compiled version of STIR. You will have to give much more information in this thread, or try to dig in more by yourself, then I might be able to help.

**Comment by olivierverdier** [comment]
Should be fixed in 0cd9cb6d0efa7655c23380489c1694d4b4422a58
